spring.application.name=config-server

server.port=8888

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.profiles.active=native

spring.cloud.config.server.native.search-locations=classpath:/config

## spring.cloud.config.server.git.uri=https://github.com/YOUR_USERNAME/config-repository.git
